### PR TITLE
Fix the seth-tp build issue because of SDK protobuf update

### PR DESCRIPTION
**Pull request by arsulegai**

### CODE REVIEW

**Comment by arsulegai** [comment]
This patch will help the developers continue using the sawtooth-seth, until the Go SDK protobuf whereabouts are finalized.

**Comment by peterschwarz** [comment]
You may need to add the clippy fixes from #117 to this PR, as both seem to need the other’s fixes to successfully build.

**Comment by arsulegai** [comment]
> You may need to add the clippy fixes from #117 to this PR, as both seem to need the other’s fixes to successfully build.

Done

**Comment by arsulegai** [comment]
There's probably more to fix, there's a cli-go which also needs a fix in the protobuf paths.

**Comment by pereirajoaoEI** [comment]
Hello everyone!
It appears that the _docker-compose up --build_ to the sawtooth-seth stills does not work.
I even tried to build the sawtooth-seth from this commit (ff897fe), but stills ends up in an error. (image below)
Do you guys have any solution?
Thank you!

@arsulegai @peterschwarz 


seth

**Pull request merged**
