### PR TITLE
Fix Seth for apt-key/gpg Proxy on Bionic

### PR DESCRIPTION
**Pull request by danintel**
gpg (through "apt-key adv") ignores http_proxy and
https_proxy settings on Bionic.
The solution is to use http with curl instead to download keys.

Signed-off-by: danintel <daniel.anderson@intel.com>

### CODE REVIEW

**Comment by danintel** [comment]
For the record here are the exact log messages:
1. For DevMode consensus errors:

```
devmode-engine-rust | ERROR | devmode_engine_rust: | ReceiveError: TimeoutError
devmode-engine-rust exited with code 1
```

2. For apt-key proxy errors:

```
Executing: /tmp/apt-key-gpghome.E9z456VMWq/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --r
ecv-keys 44FC67F19B2466EA
gpg: keyserver receive failed: Connection timed out
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.11j3dCOYV0/gpg.1.sh --keyserver hkp://p80.pool.sks-keyservers.net
:80 --recv-keys 44FC67F19B2466EA
gpg: keyserver receive failed: Cannot assign requested address
```

**Comment by danintel** [comment]
I removed the consensus fixes in `docker-compose*.yaml` and will resubmit that as a separate PR shortly.

**Comment by dplumb94** [comment]
@danintel  Looks like this one needs a rebase

**Comment by rbuysse** [comment]
This repository will be archived soon so I'm closing this PR. Thanks for your contribution!

**Pull request closed without merging**
