### PR TITLE
Adds a build_all script to create the Docker images for Seth

### PR DESCRIPTION
**Pull request by grkvlt**

### CODE REVIEW

**Comment by dplumb94** [comment]
Currently we have all the build functionality wrapped up in the docker-compose.yaml file, and running `docker-compose up --build` will automatically build all of the images before starting up containers. Additionally, `docker-compose build` can be used to just build the images without starting containers.

I am wondering if this build script provides any additional functionality?

Thanks!

**Comment by grkvlt** [comment]
Good point @dplumb94 - I sort of forgot that `docker-compose build` was a thing. But, I would like a way of creating the images that I can use where they aren't constrained by needing to work with the compose file, since eventually I want to be able to build a Sawtooth plus Seth platform that is orchestrated by other tools.

I don't think this does any harm, so why not? Eventually we want to create images using a two stage process anyway, to make them smaller, which would be decoupled from the compose file, so this would be a step towards that.

**Comment by dplumb94** [comment]
A multi-stage build approach would only need to change the Dockerfiles to toss out dependencies after the executable has been built. This wouldn't necessitate any changes to the current `docker-compose up --build` workflow

**Comment by grkvlt** [comment]
A multi-stage build would involve having to uninstall golang, rustc, cargo and so on after the build, *but* you would _still_ have the previous layers from the dockerfile, so the image would still be huge. This is not the right way to create Docker images. You need a build Dockerfile that creates the executables and caches them somewhere (for core we make .deb files, here we just store the executables in a local build dir in the repo on the host), then _another_ Dockerfile will install the minimal set of required libraries and copy the executables from the host to the image.

Here are the results of three Dockerfiles, `test-1` is just `ubuntu:xenial`, then `test-2` has `golang` installed, finally `test-3` has `golang` installed, then removed:
```
REPOSITORY                                     TAG                 IMAGE ID            CREATED             SIZE
test-3                                         latest              1184f7b369f5        5 seconds ago       538MB
test-2                                         latest              7e37631f018d        18 seconds ago      537MB
test-1                                         latest              41d13b186bdc        25 seconds ago      112MB
```

**Comment by grkvlt** [comment]
Closing after @dplumb94 suggested moving to multi-stage builds as described in https://blog.alexellis.io/mutli-stage-docker-builds/

**Pull request closed without merging**
