### PR TITLE
Update sawtooth_app_state.go

### PR DESCRIPTION
**Pull request by konsmosc**
Signed-off-by: konsmosc <kostasmoschou@gmail.com>

### CODE REVIEW

**Comment by konsmosc** [comment]
> Please update commits in this PR (do not create a new PR) with a better commit message. See:
> 
> https://chris.beams.io/posts/git-commit/

Done

**Comment by konsmosc** [comment]
I have made the commit message better here:
[https://github.com/hyperledger/sawtooth-seth/commit/3089c16e518fa8040ada6f6eb2855944c08f4ac8]
Is it something else that I have to do @vaporos ??

**Comment by peterschwarz** [comment]
Hey, this looks good now, but you will need to rebase on master, to pickup some Rust dependency changes.

**Comment by konsmosc** [comment]
> Hey, this looks good now, but you will need to rebase on master, to pickup some Rust dependency changes.

I think now it should be fine, isn't it?

**Pull request merged**
